# Dracula theme for Alacritty
# https://draculatheme.com/alacritty
#
# Color palette
# https://spec.draculatheme.com
#
# Instructions
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd

[window]
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.75

[font]
size = 8.0

[colors.primary]
background = "#282a36"
foreground = "#F6F9FC"
bright_foreground = "#F6F9FC"

[colors.cursor]
text = "#282a36"
cursor = "#F6F9FC"

[colors.vi_mode_cursor]
text = "CellBackground"
cursor = "CellForeground"

[colors.selection]
text = "CellForeground"
background = "#050607"

[colors.normal]
black = "#515860"
red = "#FF3333"
green = "#3AB1F5"
yellow = "#FFFF00"
blue = "#0088CC"
magenta = "#FF69B4"
cyan = "#1793D1"
white = "#F6F9FC"

[colors.bright]
black = "#515860"
red = "#FF3333"
green = "#3AB1F5"
yellow = "#FFFF00"
blue = "#0088CC"
magenta = "#FF69B4"
cyan = "#1793D1"
white = "#F6F9FC"

[colors.search.matches]
foreground = "#515860"
background = "#00FF00"

[colors.search.focused_match]
foreground = "#515860"
background = "#FFFF00"

[colors.footer_bar]
background = "#515860"
foreground = "#f8f8f2"

[colors.hints.start]
foreground = "#515860"
background = "#FFFF00"

[colors.hints.end]
foreground = "#FFFF00"
background = "#515860"
